In [8]:
import torch
from torch import nn
import numpy as np
import torch.nn.functional as F

x = np.random.rand(50,50)
print(x.shape)
#print(x)
tens = torch.from_numpy(x)
# [batch_size, in_channels, len].

#print(tens)
tens = tens.view(50,1,50)
#print(tens)
m = nn.Conv1d(1,20,3) 
out = m(tens.float())
print(out.size())
#print(out)
#print(m)


(50, 50)
torch.Size([50, 20, 48])


In [9]:
MaxPool = nn.MaxPool1d(kernel_size=2)
out = F.relu(out)
print(out.size())
# o = MaxPool(out)
# print(o.size())

torch.Size([50, 20, 48])


In [14]:
out = out.view(20,50,48)
l = nn.LSTM(48,48)
# for i in out:
#  (seq_len, batch, input_size)
#     c,h = l(i)
output, (h_n, c_n) = l(out)
# print(out)
# print(h_n)
# print(c_n)

RuntimeError: input must have 3 dimensions, got 2

In [13]:
#print(h.size(),c.size())
print(type(h_n[0]))
print(output.size())
print(h_n.size())
print(c_n.size())
#print(c.size())

<class 'torch.Tensor'>
torch.Size([20, 50, 48])
torch.Size([1, 50, 48])
torch.Size([1, 50, 48])


In [35]:
BI = nn.Bilinear(18,18,100)
final = BI(output,output)

In [73]:

lstm = nn.LSTM(3, 3)
inputs = [torch.randn(1, 3) for _ in range(5)]
print(inputs)
# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
print(hidden)
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

[tensor([[-1.2619, -0.3109, -2.4513]]), tensor([[ 0.9039, -1.0503, -0.3035]]), tensor([[-1.8692,  0.5329,  2.7925]]), tensor([[0.7059, 1.2776, 0.8901]]), tensor([[-2.3931,  0.5915, -0.1738]])]
(tensor([[[-0.3374, -0.4704,  0.7415]]]), tensor([[[ 2.0559, -1.3110,  0.0025]]]))


In [74]:
print(out)

tensor([[[ 0.0790, -0.0721, -0.1745]]], grad_fn=<StackBackward>)


In [75]:
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
out, hidden = lstm(inputs, hidden)

In [76]:
print(out)


tensor([[[ 0.2007, -0.1990,  0.0727]],

        [[ 0.0198, -0.1477,  0.2155]],

        [[-0.0153,  0.1476,  0.0462]],

        [[-0.1159,  0.0908, -0.1558]],

        [[ 0.0743, -0.0703, -0.1820]]], grad_fn=<StackBackward>)


In [18]:
lstm = nn.LSTM(3, 3) 
inputs = [torch.randn(1, 3) for _ in range(5)] 
# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
print(inputs)
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    print(i)
    print(i.view(1,1,-1))
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print(out)
    print(hidden)

[tensor([[-1.1434, -0.3203,  0.8715]]), tensor([[-0.4727,  0.3649,  0.1616]]), tensor([[ 0.0915, -0.4364,  0.4942]]), tensor([[-0.2069, -1.4471,  0.8516]]), tensor([[-0.8685,  0.6741,  0.8088]])]
tensor([[-1.1434, -0.3203,  0.8715]])
tensor([[[-1.1434, -0.3203,  0.8715]]])
tensor([[[-0.2865,  0.2719, -0.5144]]], grad_fn=<StackBackward>)
(tensor([[[-0.2865,  0.2719, -0.5144]]], grad_fn=<StackBackward>), tensor([[[-0.4580,  0.5403, -0.6904]]], grad_fn=<StackBackward>))
tensor([[-0.4727,  0.3649,  0.1616]])
tensor([[[-0.4727,  0.3649,  0.1616]]])
tensor([[[-0.1339,  0.1380, -0.3457]]], grad_fn=<StackBackward>)
(tensor([[[-0.1339,  0.1380, -0.3457]]], grad_fn=<StackBackward>), tensor([[[-0.2472,  0.1935, -0.5023]]], grad_fn=<StackBackward>))
tensor([[ 0.0915, -0.4364,  0.4942]])
tensor([[[ 0.0915, -0.4364,  0.4942]]])
tensor([[[-0.0470,  0.0804, -0.4023]]], grad_fn=<StackBackward>)
(tensor([[[-0.0470,  0.0804, -0.4023]]], grad_fn=<StackBackward>), tensor([[[-0.0824,  0.1699, -0.6018]]], gr